// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA91JCn8ABPUPSaiQyK7GB3O8h7jEvcbSM',
    appId: '1:548832676953:web:60114b6cc3c9acad8cb548',
    messagingSenderId: '548832676953',
    projectId: 'flutterauth-e3774',
    authDomain: 'flutterauth-e3774.firebaseapp.com',
    storageBucket: 'flutterauth-e3774.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0a01eIiVfTwPBEBYEoDTF-cEO-s2rG7U',
    appId: '1:548832676953:android:2c86bb41d38391b38cb548',
    messagingSenderId: '548832676953',
    projectId: 'flutterauth-e3774',
    storageBucket: 'flutterauth-e3774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9D5_RPID5hs1vwqfCbSJ3c7S2VReRlY',
    appId: '1:548832676953:ios:44d18fa5caf753dd8cb548',
    messagingSenderId: '548832676953',
    projectId: 'flutterauth-e3774',
    storageBucket: 'flutterauth-e3774.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC9D5_RPID5hs1vwqfCbSJ3c7S2VReRlY',
    appId: '1:548832676953:ios:9af3a7a049c20c8f8cb548',
    messagingSenderId: '548832676953',
    projectId: 'flutterauth-e3774',
    storageBucket: 'flutterauth-e3774.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
